"""Configuration for visnjan_whichneo.

Every observatory-specific rule lives here. Values marked TBD are placeholders
awaiting confirmation from Luka -- see TBD.md for the open questions.

Thresholds marked "legacy" are the defaults recovered from the observatory's
own planner (planets-new.py), so our output can be compared against its.
"""

import os

# --- Site: L01, Tican Station, Visnjan Observatory --------------------------
# Derived from the official MPC parallax constants rather than a hardcoded
# lat/lon, so the site matches exactly what Find_Orb and the MPC use for L01.
# ObsCodes.htm: "L01  13.749300.704742+0.707169Visnjan Observatory, Tican"
# These resolve to 45.2909 N, 13.74930 E, 381 m.
MPC_CODE = "L01"
SITE_LON_DEG = 13.74930
SITE_RHO_COS_PHI = 0.704742
SITE_RHO_SIN_PHI = 0.707169

# --- Data sources ------------------------------------------------------------
NEOCP_URL = "https://www.minorplanetcenter.net/iau/NEO/neocp.txt"
# Orbital parameters (e, a -> q) for everything on NEOCP, in one request.
NEOCP_INFO_URL = "https://minorplanetcenter.net/cgi-bin/cgipy/neocp_info/"
# Per-object ephemeris, generated by MPC for our site.
EPHEMERIS_URL = "https://cgi.minorplanetcenter.net/cgi-bin/confirmeph2.cgi"
NEOCP_TIMEOUT_S = 30
EPHEMERIS_TIMEOUT_S = 60
# Concurrent per-object requests. Deliberately low: MPC is a shared public
# service and the update loop has 300 s of headroom.
EPHEMERIS_WORKERS = 4

# Altitude floor handed to MPC as the `oalt` parameter, so the server never
# returns rows below it. Note this dominates MIN_ALT below -- the legacy
# planner sets minAlt=15 while also passing oalt=20, so its 15 can never fire.
MPC_SERVER_MIN_ALT = 20.0

# Only these prefixes may be fetched. Guards against following an arbitrary
# URL scraped out of a page; the legacy MPCS tool does the same.
ALLOWED_HOSTS = (
    "https://www.minorplanetcenter.net/",
    "https://cgi.minorplanetcenter.net/",
    "http://cgi.minorplanetcenter.net/",
    "https://minorplanetcenter.net/",
)

# --- Display ----------------------------------------------------------------
# The board is read at the observatory, so times are shown in Visnjan local
# time. UTC is kept alongside because that is what MPC, the plan file and the
# 80-column astrometry format all use -- the plan file stays UTC on purpose.
DISPLAY_TZ = "Europe/Zagreb"

# --- Observing night ---------------------------------------------------------
# The legacy planner treats a night as 11:00 UT to 11:00 UT the next day, so a
# session spanning midnight stays one unit and names one output file.
NIGHT_ROLLOVER_HOUR_UT = 11
# Ephemerides are interpolated this far ahead, so coordinates account for the
# time it takes to slew and settle.
INTERPOLATE_AHEAD_S = 600

# --- Horizon / dome mask -----------------------------------------------------
# Azimuth sector -> minimum observable altitude (deg). None means blocked.
# Sectors are 45 deg wide starting at 337.5; N wraps through 0.
#
# TBD -- from observer notes containing two unresolved conflicts:
#   * "northwest is 50 degrees" vs later "Northwest = 40"  -> using 40
#   * "below 30-40 degrees in the west" vs "West = 40"     -> using 40
#   * SW was never specified                               -> interpolated 30
# The legacy planner has no azimuth-dependent mask at all, only a flat floor,
# so this is knowledge we hold that its code does not.
HORIZON_MASK = [
    (337.5, 22.5, None),   # N  - "avoid north completely"
    (22.5, 67.5, 20.0),    # NE - "above 20 in South and East"
    (67.5, 112.5, 20.0),   # E
    (112.5, 157.5, 20.0),  # SE
    (157.5, 202.5, 20.0),  # S
    (202.5, 247.5, 30.0),  # SW - TBD, interpolated between S and W
    (247.5, 292.5, 40.0),  # W  - "West = 40"
    (292.5, 337.5, 40.0),  # NW - "Northwest = 40"
]
# Flat floor applied in addition to the mask.
MIN_ALT = 15.0                       # legacy
# Zenith blind spot. The observer mentioned an upper elevation limit but gave
# no value; common on fork mounts. None disables the check.
MAX_ALTITUDE = None                  # TBD

# --- Filter cascade ----------------------------------------------------------
MAX_MAG = 21.6                       # legacy (we previously used 21.7)
SUN_ALT_MAX = -15.0                  # legacy
MOON_SEP_MIN = 20.0                  # legacy
MIN_SCORE = 25                       # legacy: digest2 floor
MIN_ARC_DAYS = 0.01                  # legacy
MAX_NOT_SEEN_DAYS = 4.0              # legacy
MIN_MOTION = 0.7                     # legacy: arcsec/min, rejects main-belt
MAX_SCATTEREDNESS = (2000, 2000)     # legacy: arcsec spread of uncertainty map
SCATTEREDNESS_WARN = (1000, 800)     # legacy: warn but do not discard

# Keep only NEO-like or otherwise unusual orbits.
NEO_ONLY = True                      # legacy
NEO_Q_MAX = 1.3                      # legacy
NEO_E_MIN = 0.5                      # legacy

# Discard objects our own site has already observed.
SKIP_ALREADY_OBSERVED = True         # legacy

# --- Telescope field ---------------------------------------------------------
# Square field used to overlay the uncertainty map and report what fraction of
# an object's cloud one pointing covers.
# 2600 is Luka's figure. The legacy MPCS tool's own config (MPCS.ini) says
# FOV = 2562; 1.5% apart, so one of them is rounded or stale. Recorded here so
# the discrepancy is not lost.
FOV_ARCSEC = 2600

# --- Exposures ---------------------------------------------------------------
# The observatory's real rule, recovered from the legacy planner:
#     minutes = 10 + (magnitude - 18) * 5
# This replaces the placeholder that was here before.
EXPOSURE_BASE_MIN = 10.0
EXPOSURE_REF_MAG = 18.0
EXPOSURE_MIN_PER_MAG = 5.0
# The formula is linear and unbounded, so it goes negative for bright targets
# -- V=12.5 yields -17.5 minutes. The legacy planner prints that verbatim.
# Clamped here; ask Luka what the floor should really be.
EXPOSURE_FLOOR_MIN = 1.0             # TBD

# --- Ranking -----------------------------------------------------------------
# Default ordering is chronological by time of maximum altitude, matching the
# legacy planner: the list is a working sequence for the night, not a
# desirability ranking. The intrinsic score below is retained as a sortable
# column so the two views can be compared.
DEFAULT_SORT = "chronological"       # or "score"
RANK_WEIGHTS = {"digest2": 2.0, "arc": 1.5, "magnitude": 1.5}
ARC_SATURATE_DAYS = 3.0
MAG_BRIGHT = 15.0

# --- Cross-check -------------------------------------------------------------
# MPC's ephemeris is the source of truth, but astropy recomputes the same
# quantities independently so a silent change in MPC's page format shows up as
# a disagreement rather than as quietly wrong numbers.
CROSSCHECK = True
CROSSCHECK_ALT_TOL_DEG = 1.0
CROSSCHECK_AZ_TOL_DEG = 2.0
CROSSCHECK_MOON_TOL_DEG = 2.0

# --- Survey priorities (TBD) -------------------------------------------------
HIGH_PRIORITY_SURVEYS = []           # TBD
LOW_PRIORITY_SURVEYS = []            # TBD
BLACKLIST = []                       # TBD

# --- Storage / runtime -------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "data")
# data/ is gitignored, so a fresh clone has no such directory. Create it at
# import time: logging opens its file before anything else touches the path.
os.makedirs(DATA_DIR, exist_ok=True)
DB_PATH = os.path.join(DATA_DIR, "targets.db")
LOG_PATH = os.path.join(DATA_DIR, "update.log")
# Nightly plan files, in the legacy planner's format.
PLAN_DIR = os.path.join(BASE_DIR, "plans")
WRITE_NIGHTLY_PLAN = True

UPDATE_INTERVAL_S = 300
WEB_POLL_INTERVAL_S = 20
