"""Configuration for visnjan_whichneo.

Two different things live here, and they are now kept apart:

  * **The deployment** -- MPC endpoints, timeouts, storage paths, mail,
    accounts, ds42, the sky-map geometry. One set of these, whatever
    observatories are served.

  * **The observatories** -- loaded at the bottom from `sites/*.toml`, one
    file per site. Everything observatory-specific is a field of a Site
    rather than a module-level name here, so a module is handed the site it
    is working on instead of reaching for a global. See sites.py for the type
    and multisite.md (branch `multisite-plan`) for why.

L01's own settings, and the reasoning behind each of them, now live in
sites/L01.toml rather than in this file.
"""

import os

import sites

# --- Data sources ------------------------------------------------------------
NEOCP_URL = "https://www.minorplanetcenter.net/iau/NEO/neocp.txt"
# Orbital parameters (e, a -> q) for everything on NEOCP, in one request.
NEOCP_INFO_URL = "https://minorplanetcenter.net/cgi-bin/cgipy/neocp_info/"
# Population scores from MPC's variant orbits, and a median H per object,
# for everything on NEOCP in one request. Updated hourly. This is where the
# main-belt classification comes from rather than an a/e cut of our own, and
# where the better H for the distance calculation comes from -- it disagrees
# with neocp.txt's H by about half a magnitude, which is a quarter of the
# distance. Marked Beta by MPC, and a plain HTML table with no documented
# machine-readable form, so it is parsed defensively and its absence is never
# fatal.
NEOCP_CLASSES_URL = (
    "https://minorplanetcenter.net/mpcops/neocp/neocp_plots/info/")
# Per-object ephemeris, generated by MPC for a given site.
EPHEMERIS_URL = "https://cgi.minorplanetcenter.net/cgi-bin/confirmeph2.cgi"
NEOCP_TIMEOUT_S = 30
EPHEMERIS_TIMEOUT_S = 60
# Concurrent per-object requests. Deliberately low: MPC is a shared public
# service and the update loop has 300 s of headroom.
EPHEMERIS_WORKERS = 4

# An ephemeris is cached against a signature of the object's NEOCP row, so it
# is refetched when new astrometry changes the solution. But MPC generates it
# over a fixed window starting when it was asked, so one cached against
# unchanged astrometry still goes out of date with the clock: after a day it
# no longer covers tonight, and the night's plan silently becomes last
# night's. When a cached ephemeris has no row left at or after now, it is
# refetched -- but no more often than this, so an object that genuinely never
# rises again is not requested every single cycle.
EPHEMERIS_REFETCH_BACKOFF_S = 1800

# Only these prefixes may be fetched. Guards against following an arbitrary
# URL scraped out of a page; the legacy MPCS tool does the same.
ALLOWED_HOSTS = (
    "https://www.minorplanetcenter.net/",
    "https://cgi.minorplanetcenter.net/",
    "http://cgi.minorplanetcenter.net/",
    "https://minorplanetcenter.net/",
)

# --- Sky map -----------------------------------------------------------------
# All-sky view drawn on the board: zenith at the centre, horizon at the rim,
# radius linear in altitude.
#
# Orientation is the MAP convention -- north up, east RIGHT, south down, west
# left -- so it reads like looking down on the observatory, matching how dome
# azimuth is thought about. Note this is the mirror of a planisphere, which
# puts east on the left because you hold it up against the sky. Verified by
# the bearing to Trieste: 3.0 deg true, which must land at the top of the disc.
SKYMAP_SIZE = 560                    # px, square
SKYMAP_RINGS = (20, 40, 60, 80)      # altitude circles drawn inside the rim
SKYMAP_MOON_RING_POINTS = 180        # samples around the lunar exclusion locus

# --- Cross-check -------------------------------------------------------------
# MPC's ephemeris is the source of truth, but astropy recomputes the same
# quantities independently so a silent change in MPC's page format shows up as
# a disagreement rather than as quietly wrong numbers.
CROSSCHECK = True
CROSSCHECK_ALT_TOL_DEG = 1.0
CROSSCHECK_AZ_TOL_DEG = 2.0
CROSSCHECK_MOON_TOL_DEG = 2.0

# --- Storage / runtime -------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "data")
# data/ is gitignored, so a fresh clone has no such directory. Create it at
# import time: logging opens its file before anything else touches the path.
os.makedirs(DATA_DIR, exist_ok=True)
DB_PATH = os.path.join(DATA_DIR, "targets.db")
LOG_PATH = os.path.join(DATA_DIR, "update.log")
# Nightly plan files, in the legacy planner's format. Each site says which
# directory under here is its own (see a site's plan_dir), so this is only
# the root they are resolved against.
PLAN_DIR = os.path.join(BASE_DIR, "plans")
WRITE_NIGHTLY_PLAN = True

# --- Accounts ----------------------------------------------------------------
# Marks the session cookie Secure. Leave it off while the dome reaches the
# board over plain http://epyc:12600 -- a Secure cookie is simply not sent on
# an http connection, so turning this on early means nobody at the observatory
# can log in, with no error to explain why. Turn it on when every route in
# is https (WHICHNEO_HTTPS=1 in the environment does the same).
REQUIRE_HTTPS = os.environ.get("WHICHNEO_HTTPS", "") not in ("", "0", "no")

# Open self-service sign-up. The board is a small collaboration, not a public
# service; if it ever attracts nuisance registrations, set this false and
# create accounts with `python3 manage.py adduser <name>`.
ALLOW_SIGNUP = True

# Where the board answers from the outside. Password-reset links are absolute
# URLs in an email, so they cannot be derived from the request the way every
# other link on the site can -- a link built from a request to
# http://epyc:12600 is useless in somebody's inbox.
#
# Note this is the DEPLOYMENT's URL and has nothing to do with a Site below.
SITE_URL = os.environ.get("WHICHNEO_SITE_URL", "https://whichneo.juriclab.org")

# --- Outgoing mail ------------------------------------------------------------
# The relay at infra.juriclab.org. The password is NOT here: it comes from
# WHICHNEO_SMTP_PASSWORD or data/smtp_password, both outside the repository.
# With no password configured the site runs exactly as before, minus the
# reset link.
SMTP_HOST = os.environ.get("WHICHNEO_SMTP_HOST", "mail.infra.juriclab.org")
SMTP_PORT = int(os.environ.get("WHICHNEO_SMTP_PORT", "587"))
SMTP_USER = os.environ.get("WHICHNEO_SMTP_USER", "whichneo@infra.juriclab.org")
SMTP_FROM = os.environ.get("WHICHNEO_SMTP_FROM", "whichneo@infra.juriclab.org")
SMTP_STARTTLS = True
SMTP_TIMEOUT_S = 20

# Where the feedback form's messages go. One fixed address, never anything the
# sender can influence: a public form that mails an arbitrary recipient is an
# open relay with extra steps.
FEEDBACK_TO = os.environ.get("WHICHNEO_FEEDBACK_TO", "ds2004@uw.edu")

# What one address may send in an hour. Generous for a person, tight enough
# that the form is not worth automating against.
FEEDBACK_LIMIT = 5
FEEDBACK_WINDOW_S = 3600
FEEDBACK_MAX_CHARS = 4000

# How long a password-reset link stays good. Long enough to survive a night
# shift and a slow mail queue, short enough that a link left in an inbox is
# not a standing key to the account.
RESET_TOKEN_MAX_AGE_S = 3600

# An invitation is a different situation from a reset and needs a different
# window. A reset is asked for by someone sitting at the page, waiting; an
# hour is generous. An invitation is pushed at someone who was not expecting
# it, and the clock starts when it is minted, not when it is read -- so an
# hour means anyone invited while they are asleep, or during a mail deferral,
# gets a link that is already dead when they open it, and no way to tell that
# from a broken board.
INVITE_TOKEN_MAX_AGE_S = 86400

# --- ds42 -------------------------------------------------------------------
# The Bayesian tracklet classifier we run alongside digest2. Lives outside
# this repository on purpose -- see deploy/DS42.md for the install and
# ds42.md for what we have found with it.
#
# Off unless the install is actually present, so a clone without it, or a
# machine that never had it, behaves exactly as before. Scoring is best
# effort in every sense: a failure is logged and the cycle carries on.
DS42_ROOT = os.environ.get("WHICHNEO_DS42_ROOT", "/home/devanshi-s04/ds42")
DS42_SRC = os.path.join(DS42_ROOT, "src")
DS42_BIN = os.path.join(DS42_ROOT, "venv", "bin", "ds42")
DS42_MODEL = os.path.join(DS42_ROOT, "data", "digest2.model.csv")
DS42_OBSCODES = os.path.join(DS42_ROOT, "data", "ObsCodesF.html")
DS42_ENABLED = os.environ.get("WHICHNEO_DS42", "1") not in ("0", "no", "")
# One subprocess scores every object that needs one, so this bounds the whole
# batch, not a single object. Measured: 73 objects in 4.8 s including the
# 1.5 s model load.
DS42_TIMEOUT_S = 180

UPDATE_INTERVAL_S = 300
WEB_POLL_INTERVAL_S = 20



# =============================================================================
# The observatories this deployment serves
# =============================================================================
# One TOML file per site in sites/, loaded at import. L01 is site 1 and is
# described by sites/L01.toml exactly as any other observatory would be --
# nothing in the code knows it by name, so a bug in its path is found rather
# than hidden.
#
# A bad site file raises here rather than being skipped with a warning. A
# site whose horizon mask failed to load would still produce a board, and
# that board would be confidently wrong about where a telescope can point.
SITES_DIR = os.environ.get("WHICHNEO_SITES_DIR",
                           os.path.join(BASE_DIR, "sites"))
SITES = sites.load_dir(SITES_DIR)

# The site a request that names none gets. Lowest id, which is L01 here, so a
# signed-out visitor sees exactly the board they saw before several sites
# existed.
DEFAULT_SITE = SITES[min(SITES)]

# How many observatories this deployment will serve at once, counting both
# the ones defined by a file and the ones created through sign-up.
#
# A real number rather than a vague worry. Only the ephemeris fetch is
# per-observatory, measured over 300 cycles on the live board at 1.1 fetches
# per cycle -- about 306 a day per site. Twenty-five is therefore roughly 5
# requests a minute and ~8,000 fetches a day against MPC: comfortably inside
# what a small institutional service can justify without asking anyone's
# permission, with headroom to raise it once real usage is visible.
ACTIVE_SITE_CAP = int(os.environ.get("WHICHNEO_SITE_CAP", "25"))
