"""Configuration for visnjan_whichneo.

Two different things live here, and they are now kept apart:

  * **The deployment** -- MPC endpoints, timeouts, storage paths, mail,
    accounts, ds42, the sky-map geometry. One set of these, whatever
    observatories are served.

  * **The default site** -- L01, built at the bottom as `DEFAULT_SITE`.
    Everything observatory-specific is a field of that object rather than a
    module-level name, so a module is handed the site it is working on
    instead of reaching for a global. See sites.py for the type and
    multisite.md (branch `multisite-plan`) for why.

Values marked TBD are placeholders awaiting confirmation from Luka -- see
TBD.md for the open questions.

Thresholds marked "legacy" are the defaults recovered from the observatory's
own planner (planets-new.py), so our output can be compared against its.
"""

import os

from sites import Site

# --- Data sources ------------------------------------------------------------
NEOCP_URL = "https://www.minorplanetcenter.net/iau/NEO/neocp.txt"
# Orbital parameters (e, a -> q) for everything on NEOCP, in one request.
NEOCP_INFO_URL = "https://minorplanetcenter.net/cgi-bin/cgipy/neocp_info/"
# Per-object ephemeris, generated by MPC for a given site.
EPHEMERIS_URL = "https://cgi.minorplanetcenter.net/cgi-bin/confirmeph2.cgi"
NEOCP_TIMEOUT_S = 30
EPHEMERIS_TIMEOUT_S = 60
# Concurrent per-object requests. Deliberately low: MPC is a shared public
# service and the update loop has 300 s of headroom.
EPHEMERIS_WORKERS = 4

# An ephemeris is cached against a signature of the object's NEOCP row, so it
# is refetched when new astrometry changes the solution. But MPC generates it
# over a fixed window starting when it was asked, so one cached against
# unchanged astrometry still goes out of date with the clock: after a day it
# no longer covers tonight, and the night's plan silently becomes last
# night's. When a cached ephemeris has no row left at or after now, it is
# refetched -- but no more often than this, so an object that genuinely never
# rises again is not requested every single cycle.
EPHEMERIS_REFETCH_BACKOFF_S = 1800

# Only these prefixes may be fetched. Guards against following an arbitrary
# URL scraped out of a page; the legacy MPCS tool does the same.
ALLOWED_HOSTS = (
    "https://www.minorplanetcenter.net/",
    "https://cgi.minorplanetcenter.net/",
    "http://cgi.minorplanetcenter.net/",
    "https://minorplanetcenter.net/",
)

# --- Sky map -----------------------------------------------------------------
# All-sky view drawn on the board: zenith at the centre, horizon at the rim,
# radius linear in altitude.
#
# Orientation is the MAP convention -- north up, east RIGHT, south down, west
# left -- so it reads like looking down on the observatory, matching how dome
# azimuth is thought about. Note this is the mirror of a planisphere, which
# puts east on the left because you hold it up against the sky. Verified by
# the bearing to Trieste: 3.0 deg true, which must land at the top of the disc.
SKYMAP_SIZE = 560                    # px, square
SKYMAP_RINGS = (20, 40, 60, 80)      # altitude circles drawn inside the rim
SKYMAP_MOON_RING_POINTS = 180        # samples around the lunar exclusion locus

# --- Cross-check -------------------------------------------------------------
# MPC's ephemeris is the source of truth, but astropy recomputes the same
# quantities independently so a silent change in MPC's page format shows up as
# a disagreement rather than as quietly wrong numbers.
CROSSCHECK = True
CROSSCHECK_ALT_TOL_DEG = 1.0
CROSSCHECK_AZ_TOL_DEG = 2.0
CROSSCHECK_MOON_TOL_DEG = 2.0

# --- Storage / runtime -------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, "data")
# data/ is gitignored, so a fresh clone has no such directory. Create it at
# import time: logging opens its file before anything else touches the path.
os.makedirs(DATA_DIR, exist_ok=True)
DB_PATH = os.path.join(DATA_DIR, "targets.db")
LOG_PATH = os.path.join(DATA_DIR, "update.log")
# Nightly plan files, in the legacy planner's format.
PLAN_DIR = os.path.join(BASE_DIR, "plans")
WRITE_NIGHTLY_PLAN = True

# --- Accounts ----------------------------------------------------------------
# Marks the session cookie Secure. Leave it off while the dome reaches the
# board over plain http://epyc:12600 -- a Secure cookie is simply not sent on
# an http connection, so turning this on early means nobody at the observatory
# can log in, with no error to explain why. Turn it on when every route in
# is https (WHICHNEO_HTTPS=1 in the environment does the same).
REQUIRE_HTTPS = os.environ.get("WHICHNEO_HTTPS", "") not in ("", "0", "no")

# Open self-service sign-up. The board is a small collaboration, not a public
# service; if it ever attracts nuisance registrations, set this false and
# create accounts with `python3 manage.py adduser <name>`.
ALLOW_SIGNUP = True

# Where the board answers from the outside. Password-reset links are absolute
# URLs in an email, so they cannot be derived from the request the way every
# other link on the site can -- a link built from a request to
# http://epyc:12600 is useless in somebody's inbox.
#
# Note this is the DEPLOYMENT's URL and has nothing to do with a Site below.
SITE_URL = os.environ.get("WHICHNEO_SITE_URL", "https://whichneo.juriclab.org")

# --- Outgoing mail ------------------------------------------------------------
# The relay at infra.juriclab.org. The password is NOT here: it comes from
# WHICHNEO_SMTP_PASSWORD or data/smtp_password, both outside the repository.
# With no password configured the site runs exactly as before, minus the
# reset link.
SMTP_HOST = os.environ.get("WHICHNEO_SMTP_HOST", "mail.infra.juriclab.org")
SMTP_PORT = int(os.environ.get("WHICHNEO_SMTP_PORT", "587"))
SMTP_USER = os.environ.get("WHICHNEO_SMTP_USER", "whichneo@infra.juriclab.org")
SMTP_FROM = os.environ.get("WHICHNEO_SMTP_FROM", "whichneo@infra.juriclab.org")
SMTP_STARTTLS = True
SMTP_TIMEOUT_S = 20

# How long a password-reset link stays good. Long enough to survive a night
# shift and a slow mail queue, short enough that a link left in an inbox is
# not a standing key to the account.
RESET_TOKEN_MAX_AGE_S = 3600

# An invitation is a different situation from a reset and needs a different
# window. A reset is asked for by someone sitting at the page, waiting; an
# hour is generous. An invitation is pushed at someone who was not expecting
# it, and the clock starts when it is minted, not when it is read -- so an
# hour means anyone invited while they are asleep, or during a mail deferral,
# gets a link that is already dead when they open it, and no way to tell that
# from a broken board.
INVITE_TOKEN_MAX_AGE_S = 86400

# --- ds42 -------------------------------------------------------------------
# The Bayesian tracklet classifier we run alongside digest2. Lives outside
# this repository on purpose -- see deploy/DS42.md for the install and
# ds42.md for what we have found with it.
#
# Off unless the install is actually present, so a clone without it, or a
# machine that never had it, behaves exactly as before. Scoring is best
# effort in every sense: a failure is logged and the cycle carries on.
DS42_ROOT = os.environ.get("WHICHNEO_DS42_ROOT", "/home/devanshi-s04/ds42")
DS42_SRC = os.path.join(DS42_ROOT, "src")
DS42_BIN = os.path.join(DS42_ROOT, "venv", "bin", "ds42")
DS42_MODEL = os.path.join(DS42_ROOT, "data", "digest2.model.csv")
DS42_OBSCODES = os.path.join(DS42_ROOT, "data", "ObsCodesF.html")
DS42_ENABLED = os.environ.get("WHICHNEO_DS42", "1") not in ("0", "no", "")
# One subprocess scores every object that needs one, so this bounds the whole
# batch, not a single object. Measured: 73 objects in 4.8 s including the
# 1.5 s model load.
DS42_TIMEOUT_S = 180

UPDATE_INTERVAL_S = 300
WEB_POLL_INTERVAL_S = 20


# =============================================================================
# The default site
# =============================================================================
# Everything below describes one observatory. It is passed to the modules that
# need it rather than read from here, so that a second observatory is a second
# Site rather than a second copy of this file.

# --- Horizon / dome mask -----------------------------------------------------
# Azimuth sector -> (start, end, minimum observable altitude, hardness).
# A minimum of None means the whole sector is discouraged at every altitude.
# Sectors are 45 deg wide starting at 337.5; N wraps through 0.
#
# HARDNESS is the important field:
#
#   "soft"  the sky there is poor, not unreachable. Rows are KEPT and the
#           target stays in the queue carrying a warning. Nothing is deleted.
#   "hard"  the telescope genuinely cannot point there -- terrain, a building,
#           a mount limit. Rows are rejected outright.
#
# Everything is soft today because every limit we have is a preference, not an
# obstruction: north is avoided because Trieste sits 41 km away at bearing 3
# deg and lights up that sky, not because anything blocks it. Deleting targets
# for that reason would mean an impactor discovered in the north simply never
# appeared on this board. It is also how the observatory's own planner behaves
# -- planets-new.py has no azimuth mask at all, only a flat altitude floor.
#
# Mark a sector "hard" only once Luka confirms it is a physical obstruction.
#
# TBD -- from observer notes containing two unresolved conflicts:
#   * "northwest is 50 degrees" vs later "Northwest = 40"  -> using 40
#   * "below 30-40 degrees in the west" vs "West = 40"     -> using 40
#   * SW was never specified                               -> interpolated 30
_L01_HORIZON_MASK = [
    (337.5, 22.5, None, "soft"),   # N  - "avoid north completely" (Trieste)
    (22.5, 67.5, 20.0, "soft"),    # NE - "above 20 in South and East"
    (67.5, 112.5, 20.0, "soft"),   # E
    (112.5, 157.5, 20.0, "soft"),  # SE
    (157.5, 202.5, 20.0, "soft"),  # S
    (202.5, 247.5, 30.0, "soft"),  # SW - TBD, interpolated between S and W
    (247.5, 292.5, 40.0, "soft"),  # W  - "West = 40"
    (292.5, 337.5, 40.0, "soft"),  # NW - "Northwest = 40"
]

# --- Keep-out wedges: hard, and about the equipment ---------------------------
# Sky the telescope must not be pointed at, whatever else is true.
#
# Deliberately NOT part of the horizon mask. That mask is advisory -- it
# describes sky that is poor because of Trieste's light dome, and it never
# removes a target, because an impactor discovered in a light-polluted
# direction still has to appear on the board. These are the opposite: a slew
# into one risks damaging the mount, so they reject outright and no display
# setting, filter or view can bring the affected rows back.
#
# Each entry is (az_from, az_to, min_altitude, reason). The arc runs CLOCKWISE
# from az_from to az_to, so (270, 45) is west -> north -> north-east, the
# northern half, and NOT the southern one. Getting that backwards would cut
# 87% of a typical night's rows rather than 9%.
#
# Below min_altitude inside the arc is forbidden; above it is allowed.
# 247.5 rather than 270: the western edge started at due west, and a target
# tracking down the west-south-west slipped under it for a whole night --
# P22pZo5 ran from azimuth 189 to 269 and never once entered the wedge, while
# being far enough west to be a problem. 247.5 is the W sector's own boundary,
# so the rule reads as "W, NW, N and NE below 70 degrees" rather than as an
# arbitrary number.
#
# This has now moved once in response to a target someone spotted. Fitting a
# safety limit to individual complaints will keep finding gaps: the real
# answer is the mount's actual limit from the observatory, which is open
# question 1 in TBD.md. Find_Orb supports a continuous horizon profile
# (site_L01.txt) if L01 has one, and we should use it directly if so.
_L01_KEEPOUT_WEDGES = [
    (247.5, 45.0, 70.0, "mount/dome collision risk"),
]

# --- Frames: the observatory's own speed table --------------------------------
# Given by Luka. A fixed number of frames for every target, with the length of
# each frame set by how fast the object is moving -- the faster it goes, the
# shorter each frame has to be to stop it trailing across the detector.
#
#   0-5 "/min -> 30 s,  5-25 -> 15 s,  25-50 -> 10 s,
#   50-100    ->  5 s, 100-200 -> 2 s,  200+  ->  1 s
#
# Upper bound INCLUSIVE, so a target at exactly 25.00 "/min gets 15 s, not 10.
# MPC reports motion to two decimals, so exact boundary values are rare but do
# occur.
#
# This answers what PR #3 was blocked on. That draft derived frame length from
# a trailing budget and derived the count from the magnitude rule; the
# observatory has a table instead, so the table wins.
#
# Note this is a SEPARATE quantity from the exposure_* fields. Those give
# obsExposure -- total integration in minutes, from magnitude, inherited from
# planets-new.py. This gives the per-frame instruction, from speed. They are
# not meant to agree and generally do not: a slow target here gets 36 x 30 s =
# 18 minutes on sky while its obsExposure asks for around 27.
_L01_SPEED_BANDS = [                 # (max "/min inclusive, seconds per frame)
    (5.0, 30),
    (25.0, 15),
    (50.0, 10),
    (100.0, 5),
    (200.0, 2),
]

# L01, Tican Station, Visnjan Observatory.
#
# Derived from the official MPC parallax constants rather than a hardcoded
# lat/lon, so the site matches exactly what Find_Orb and the MPC use for L01.
# ObsCodes.htm: "L01  13.749300.704742+0.707169Visnjan Observatory, Tican"
# These resolve to 45.2909 N, 13.74930 E, 381 m.
DEFAULT_SITE = Site(
    obscode="L01",
    lon_deg=13.74930,
    rho_cos_phi=0.704742,
    rho_sin_phi=0.707169,

    # The board is read at the observatory, so times are shown in Visnjan
    # local time. UTC is kept alongside because that is what MPC, the plan
    # file and the 80-column astrometry format all use -- the plan file stays
    # UTC on purpose.
    display_tz="Europe/Zagreb",
    # The legacy planner treats a night as 11:00 UT to 11:00 UT the next day,
    # so a session spanning midnight stays one unit and names one output file.
    night_rollover_hour_ut=11,

    horizon_mask=_L01_HORIZON_MASK,
    sector_names=["N", "NE", "E", "SE", "S", "SW", "W", "NW"],
    keepout_wedges=_L01_KEEPOUT_WEDGES,
    min_alt=15.0,                    # legacy
    # Zenith blind spot. The observer mentioned an upper elevation limit but
    # gave no value; common on fork mounts. None disables the check.
    max_altitude=None,               # TBD
    # Note this dominates min_alt above -- the legacy planner sets minAlt=15
    # while also passing oalt=20, so its 15 can never fire.
    mpc_server_min_alt=20.0,

    # Square field used to overlay the uncertainty map and report what
    # fraction of an object's cloud one pointing covers. 2600 is Luka's
    # figure. The legacy MPCS tool's own config (MPCS.ini) says FOV = 2562;
    # 1.5% apart, so one of them is rounded or stale. Recorded here so the
    # discrepancy is not lost.
    fov_arcsec=2600,
    # Ephemerides are interpolated this far ahead, so coordinates account for
    # the time it takes to slew and settle.
    interpolate_ahead_s=600,

    # --- Filter cascade ---
    max_mag=21.6,                    # legacy (we previously used 21.7)
    sun_alt_max=-15.0,               # legacy
    moon_sep_min=20.0,               # legacy
    min_score=25,                    # legacy: digest2 floor
    min_arc_days=0.01,               # legacy
    max_not_seen_days=4.0,           # legacy
    min_motion=0.7,                  # legacy: arcsec/min, rejects main-belt
    max_scatteredness=(2000, 2000),  # legacy: arcsec spread of uncertainty map
    scatteredness_warn=(1000, 800),  # legacy: warn but do not discard
    # Keep only NEO-like or otherwise unusual orbits.
    neo_only=True,                   # legacy
    neo_q_max=1.3,                   # legacy
    neo_e_min=0.5,                   # legacy
    # Discard objects our own site has already observed.
    skip_already_observed=True,      # legacy
    blacklist=[],                    # TBD
    high_priority_surveys=[],        # TBD
    low_priority_surveys=[],         # TBD

    # --- Exposures ---
    # The observatory's real rule, recovered from the legacy planner:
    #     minutes = 10 + (magnitude - 18) * 5
    exposure_base_min=10.0,
    exposure_ref_mag=18.0,
    exposure_min_per_mag=5.0,
    # The formula is linear and unbounded, so it goes negative for bright
    # targets -- V=12.5 yields -17.5 minutes. The legacy planner prints that
    # verbatim. Clamped here; ask Luka what the floor should really be.
    exposure_floor_min=1.0,          # TBD
    exposure_frames=36,
    exposure_speed_bands=_L01_SPEED_BANDS,
    exposure_fastest_sec=1,          # anything above the last band

    # --- Ranking ---
    # Default ordering is chronological by time of maximum altitude, matching
    # the legacy planner: the list is a working sequence for the night, not a
    # desirability ranking. The intrinsic score is retained as a sortable
    # column so the two views can be compared.
    default_sort="chronological",    # or "score"
    rank_weights={"digest2": 2.0, "arc": 1.5, "magnitude": 1.5},
    arc_saturate_days=3.0,
    mag_bright=15.0,
)
